name: Build workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Display dotnet version
        run: dotnet --version
      - name: Build the project
        run: |
          dotnet build
